//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroll.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_Salary
    {
        public d_Salary()
        {
            this.d_Payment = new HashSet<d_Payment>();
        }
    
        public string SalaryId { get; set; }
        public string Username { get; set; }
        public decimal BasicSalary { get; set; }
    
        public virtual ICollection<d_Payment> d_Payment { get; set; }
        public virtual m_User m_User { get; set; }
    }
}
