//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroll.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class m_Rate
    {
        public m_Rate()
        {
            this.d_AdditionalSalary = new HashSet<d_AdditionalSalary>();
        }
    
        public string RateId { get; set; }
        public string RateName { get; set; }
        public decimal RateValue { get; set; }
        public string RateType { get; set; }
    
        public virtual ICollection<d_AdditionalSalary> d_AdditionalSalary { get; set; }
    }
}
