//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroll.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_AdditionalSalary
    {
        public string AdditionalSalaryId { get; set; }
        public string Username { get; set; }
        public string RateId { get; set; }
    
        public virtual m_User m_User { get; set; }
        public virtual m_Rate m_Rate { get; set; }
    }
}
