//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroll.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_Payment
    {
        public string PaymentId { get; set; }
        public string Username { get; set; }
        public string SalaryId { get; set; }
        public DateTime PaymentDate { get; set; }
        public int PaymentMonth { get; set; }
        public int PaymentYear { get; set; }
        public bool Approved { get; set; }
        public string Note { get; set; }
    
        public virtual m_User m_User { get; set; }
        public virtual d_Salary d_Salary { get; set; }
    }
}
