//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroll.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_EMP_SALARY
    {
        public string SALARY_ID { get; set; }
        public string USERNAME { get; set; }
        public Nullable<decimal> BASIC_SALARY { get; set; }
    
        public virtual M_USER M_USER { get; set; }
    }
}
