//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroll.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_RATES
    {
        public M_RATES()
        {
            this.T_ADDITIONAL_PAYMENT = new HashSet<T_ADDITIONAL_PAYMENT>();
        }
    
        public string RATE_ID { get; set; }
        public string RATE_NAME { get; set; }
        public Nullable<decimal> RATE_VALUE { get; set; }
        public string RATE_TYPE { get; set; }
    
        public virtual ICollection<T_ADDITIONAL_PAYMENT> T_ADDITIONAL_PAYMENT { get; set; }
    }
}
