//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroll.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_USER
    {
        public M_USER()
        {
            this.M_EMP_SALARY = new HashSet<M_EMP_SALARY>();
            this.T_DAYOFF = new HashSet<T_DAYOFF>();
            this.T_PAYMENT = new HashSet<T_PAYMENT>();
        }
    
        public string USERNAME { get; set; }
        public string USERPASS { get; set; }
        public string USER_CATEGORY { get; set; }
    
        public virtual ICollection<M_EMP_SALARY> M_EMP_SALARY { get; set; }
        public virtual ICollection<T_DAYOFF> T_DAYOFF { get; set; }
        public virtual ICollection<T_PAYMENT> T_PAYMENT { get; set; }
    }
}
