//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroll.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PayrollEntities : DbContext
    {
        public PayrollEntities()
            : base("name=PayrollEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<M_EMP_SALARY> M_EMP_SALARY { get; set; }
        public DbSet<M_RATES> M_RATES { get; set; }
        public DbSet<M_USER> M_USER { get; set; }
        public DbSet<T_ADDITIONAL_PAYMENT> T_ADDITIONAL_PAYMENT { get; set; }
        public DbSet<T_DAYOFF> T_DAYOFF { get; set; }
        public DbSet<T_PAYMENT> T_PAYMENT { get; set; }
    }
}
